# Generated by Django 5.2.7 on 2025-11-20 17:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='helpful',
            new_name='is_helpful',
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='confidence_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='freshness_label',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='freshness_score',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='produce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.produce'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.produce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
