# Generated by Django 5.2.7 on 2025-11-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_rename_helpful_feedback_is_helpful_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
