# Generated by Django 5.2.7 on 2025-11-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_alter_image_image_path'),
        ('ui', '0004_userprofile'),
    ]

    operations = [
    ]
